### ISSUE TITLE
Latest nodejs - npm install fails on Windows 7?

### ISSUE THREAD

**Issue by brian428** [michaelficarra/CoffeeScriptRedux#96]
I realize Windows seems to be the less common platform folks are using, but it seems that trying to install CSR via npm install fails. Anyone have any tips? Is something wrong with the package, or am I just doing something wrong? Here's the console output I get when I try to install the package. As you can see, I'm using the latest node.js and npm (0.8.14 and 1.1.65).

```
C:\Developer\Tools\javascript\coffeescriptredux>npm install
npm http GET https://registry.npmjs.org/StringScanner
npm ERR! git clone git://github.com/michaelficarra/cscodegen.git CreateProcessW: The system cannot find the file specified.
npm WARN optional dep failed, continuing cscodegen@git://github.com/michaelficarra/cscodegen.git#73fd7202ac086c26f18c9d56f025b18b3c6f5383
npm http GET https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/escodegen
npm http GET https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/mocha
npm http GET https://registry.npmjs.org/browserify
npm ERR! git clone git://github.com/dmajda/pegjs.git CreateProcessW: The system cannot find the file specified.
npm ERR! Error: `git "clone" "git://github.com/dmajda/pegjs.git" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\npm-29116\\1352571886148-0.6870176473166794"` failed with 127
npm ERR!     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\exec.js:56:20)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:99:17)
npm ERR!     at Process._handle.onexit (child_process.js:678:10)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Developer\Tools\javascript\coffeescriptredux
npm ERR! node -v v0.8.14
npm ERR! npm -v 1.1.65
npm http 304 https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/StringScanner
npm http 304 https://registry.npmjs.org/escodegen
npm http 304 https://registry.npmjs.org/mocha
npm http 304 https://registry.npmjs.org/browserify
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Developer\Tools\javascript\coffeescriptredux\npm-debug.log
npm ERR! not ok code 0

C:\Developer\Tools\javascript\coffeescriptredux>
```

**Comment by dokuboyejo** [comment]
I just had a similar issue, the following helped me resolve it:

git config --global url."https://github.com/".insteadOf git@github.com:
git config --global url."https://".insteadOf git://
